
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vttanwzodshofhycuqjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dGFud3pvZHNob2ZoeWN1cWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NzAyNjQsImV4cCI6MjA1NjE0NjI2NH0.wxYWRpXp-Uqn-uLeH4tD-xEkelzybxWjNT8FaRGfx6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Custom function to check if the blocked_users table exists
export const checkBlockedUsersTable = async () => {
  try {
    // Simply try to select from the table to see if it exists
    const { error } = await supabase
      .from('blocked_users')
      .select('*')
      .limit(1);
    
    // If there's no error, the table exists
    return !error;
  } catch (error) {
    console.error('Error checking if blocked_users table exists:', error);
    return false;
  }
};
