
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vttanwzodshofhycuqjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dGFud3pvZHNob2ZoeWN1cWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NzAyNjQsImV4cCI6MjA1NjE0NjI2NH0.wxYWRpXp-Uqn-uLeH4tD-xEkelzybxWjNT8FaRGfx6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Custom function to check if the blocked_users table exists
export const checkBlockedUsersTable = async () => {
  try {
    // Try to query information_schema to check if the table exists
    const { data, error } = await supabase
      .rpc('check_if_table_exists_in_schema', { table_name: 'blocked_users', schema_name: 'public' });
    
    if (error) {
      console.error('Error checking table existence:', error);
      return false;
    }
    
    return data === true;
  } catch (error) {
    console.error('Error checking if blocked_users table exists:', error);
    return false;
  }
};
